export const COMPANY_NAME_LIST = [
  '杭州白纱梦境婚纱',
  '宁波纯白花园婚纱礼服',
  '合肥樱花浪漫婚纱礼服馆',
  '昆明花嫁时光婚纱',
  '苏州月下浪漫婚纱定制',
  '幸福婚纱',
  '杭州桂冠婚纱礼服馆',
  '爱的礼赞婚纱礼服馆',
  '梦幻婚纱礼服',
  '星河浪漫',
  'BridalDreams婚纱',
  '幸福礼赞',
  '爱的花园',
  '星光婚纱',
  '纯白典雅',
  '月影浪漫婚纱定制',
  '花漾婚纱',
  '经典婚纱',
  '童话婚纱',
  '缘定礼服',
  'Bridal Dreams婚纱',
  'Blissful Gowns',
  'Starlight Bridal',
  'Pure Elegance Bridal',
  'Moonlit Bride',
  'Floral Grace Bridal',
  'Timeless Beauty Bridal',
  'Fairytale Bridal',
  'Destiny Gowns',
  'Angelic Gowns',
  'Honeymoon Bridal',
  'Romance Moments Bridal',
  'Eternal Love Bridal',
  'Rosy Bride',
  'Dream Weavers Bridal',
  'Prism Bridal',
  'Wedding Ode Bridal',
  'Celestial Bridal',
  'Blossom Sea Bridal',
  'Poetic White Bridal',
  'Star Wish Gowns',
  'Bliss Journey Bridal',
  'Elegant Bride',
  'Golden Bride Bridal',
  'Erosia Bridal',
  'Embrace Bridal',
  'Luminous Bridal',
  'Sunflower Bridal',
  'Cherish Bridal',
  '天使婚纱轻奢婚纱',
  '蜜月婚纱轻奢',
  '浪漫时刻',
  '永恒爱恋',
  '玫瑰情缘',
  '梦织婚纱',
  '幻彩礼殿',
  '婚典礼赞婚纱礼服',
  '环星婚纱',
  '花海漫漫',
  '诗意白纱',
  '星愿礼服',
  '幸福之旅',
  '唯美婚纱',
  '金色婚典',
  '艾罗莎婚纱',
  '簇拥婚纱',
  '流光礼堂',
  '向阳花婚纱礼服馆',
  '珍爱婚纱礼服馆',
  '影Shadow婚纱',
  '梦露婚纱',
  '纯净礼纱',
  '花瓣礼赞',
  '幸福星空',
  '嫣然浪漫婚纱礼服馆',
  '缘梦礼服',
  '丝绸花园',
  '婚礼物语工作室',
  '极光婚纱',
  '爱之印记',
  '月光礼堂',
  '心愿婚纱',
  '珠光浪漫',
  '馨香婚纱',
  '爱的缎带',
  '白鸽婚纱',
  '天穹礼纱',
  '花坊婚纱',
  '宁静婚纱',
  'Illusion Bridal',
  'Dream Glow Bridal',
  'Pure Bliss Bridal',
  'Petal Praise Bridal',
  'Blissful Sky Bridal',
  'Radiant Bride',
  'Dream of Destiny Bridal',
  'Silk Garden Bridal',
  'Wedding Whisper Bridal',
  'Aurora Bridal',
  'Love Imprint Bridal',
  'Moonlight Hall Bridal',
  'Heart Desire Bridal',
  'Pearl Shine Bridal',
  'Fragrant Bridal',
  'Ribbon of Love Bridal',
  'Dove Bridal',
  'Celestial Canopy Bridal',
  'Blossom Atelier Bridal',
  'Serenity Bridal',
];

export const PRODUCT_NAME_LIST = ['婚纱', '礼服', '秀禾', '西服', '伴娘服'];
